#!/usr/bin/env bash
# Script to configure site redirection in nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@mstafa-alx permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
