#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

sudo apt-get -y update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Define the Nginx server configuration with custom 404 handling
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   add_header X-Served-By $HOSTNAME;
   root /etc/nginx/html;
   index index.html;

   location /redirect_me {
      return 301 https://www.youtube.com/;
   }

   error_page 404 /404.html;
   location = /404.html {
      root /etc/nginx/html;
      internal;
   }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
