#!/usr/bin/env bash
# display Best School 10 times, and Hi for the 9th iteration.

counter=0

while [$counter -lt 11 ][
do
	if [ $counter = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done

