#!/usr/bin/env bash
# display Best School 10 times, and Hi for the 9th iteration.

counter=0

while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	((counter++))
done
